<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-05T16:38:40 IST" name="Suite" finished-at="2024-08-05T16:39:49 IST" duration-ms="69291">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.SubmitOrder()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" name="SubmitOrder" class="com.example.SeleniumDesign.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest3.SubmitOrder(java.util.HashMap)[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" name="SubmitOrder" class="com.example.SeleniumDesign.SubmitOrderTest3"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-08-05T16:38:40 IST" name="SubmitOrderTest3" finished-at="2024-08-05T16:39:21 IST" duration-ms="40769">
      <class name="com.example.SeleniumDesign.SubmitOrderTest3">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" started-at="2024-08-05T16:38:40 IST" name="LaunchApplication" finished-at="2024-08-05T16:38:48 IST" duration-ms="7326" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" started-at="2024-08-05T16:38:48 IST" name="SubmitOrder" data-provider="getData" finished-at="2024-08-05T16:38:56 IST" duration-ms="8037" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Simmu@15, product=ADIDAS ORIGINAL, email=email15@example.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" started-at="2024-08-05T16:38:56 IST" name="TearDown" finished-at="2024-08-05T16:38:56 IST" duration-ms="260" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" started-at="2024-08-05T16:38:56 IST" name="LaunchApplication" finished-at="2024-08-05T16:39:03 IST" duration-ms="6744" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" started-at="2024-08-05T16:39:03 IST" name="SubmitOrder" data-provider="getData" finished-at="2024-08-05T16:39:12 IST" duration-ms="8983" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Simmu@15, product=ZARA COAT 3, email=email15@example.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" started-at="2024-08-05T16:39:12 IST" name="TearDown" finished-at="2024-08-05T16:39:12 IST" duration-ms="235" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" started-at="2024-08-05T16:39:12 IST" name="LaunchApplication" finished-at="2024-08-05T16:39:19 IST" duration-ms="7080" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" started-at="2024-08-05T16:39:19 IST" name="OrderHistoryTest" finished-at="2024-08-05T16:39:20 IST" depends-on-methods="com.example.SeleniumDesign.SubmitOrderTest3.SubmitOrder" duration-ms="1485" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.example.SeleniumDesign.SubmitOrderTest3@78641d23]" started-at="2024-08-05T16:39:20 IST" name="TearDown" finished-at="2024-08-05T16:39:21 IST" duration-ms="277" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.example.SeleniumDesign.SubmitOrderTest3 -->
    </test> <!-- SubmitOrderTest3 -->
    <test started-at="2024-08-05T16:39:21 IST" name="ErrorValidation" finished-at="2024-08-05T16:39:49 IST" duration-ms="28082">
      <class name="com.example.SeleniumDesign.ErrorValidation">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" started-at="2024-08-05T16:39:21 IST" name="LaunchApplication" finished-at="2024-08-05T16:39:26 IST" duration-ms="5226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" started-at="2024-08-05T16:39:26 IST" name="ProductErrorValidation" finished-at="2024-08-05T16:39:32 IST" duration-ms="5185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" started-at="2024-08-05T16:39:32 IST" name="TearDown" finished-at="2024-08-05T16:39:32 IST" duration-ms="226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" started-at="2024-08-05T16:39:32 IST" name="LaunchApplication" finished-at="2024-08-05T16:39:38 IST" duration-ms="5778" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method retried="true" signature="SubmitOrder()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" started-at="2024-08-05T16:39:38 IST" name="SubmitOrder" finished-at="2024-08-05T16:39:40 IST" duration-ms="2259" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.example.SeleniumDesign.ErrorValidation.SubmitOrder(ErrorValidation.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" started-at="2024-08-05T16:39:40 IST" name="TearDown" finished-at="2024-08-05T16:39:40 IST" duration-ms="163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" started-at="2024-08-05T16:39:40 IST" name="LaunchApplication" finished-at="2024-08-05T16:39:46 IST" duration-ms="6461" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="SubmitOrder()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" started-at="2024-08-05T16:39:46 IST" name="SubmitOrder" finished-at="2024-08-05T16:39:48 IST" duration-ms="1771" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.example.SeleniumDesign.ErrorValidation.SubmitOrder(ErrorValidation.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:com.example.SeleniumDesign.ErrorValidation@19e4fcac]" started-at="2024-08-05T16:39:49 IST" name="TearDown" finished-at="2024-08-05T16:39:49 IST" duration-ms="405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.example.SeleniumDesign.ErrorValidation -->
    </test> <!-- ErrorValidation -->
  </suite> <!-- Suite -->
</testng-results>
